//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_URUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_URUN()
        {
            this.TBL_SIPARISKALEMI = new HashSet<TBL_SIPARISKALEMI>();
            this.TBL_YORUM = new HashSet<TBL_YORUM>();
            this.TBL_URUNOZELLIK = new HashSet<TBL_URUNOZELLIK>();
            this.TBL_FAVORI = new HashSet<TBL_FAVORI>();
            this.TBL_SEPET = new HashSet<TBL_SEPET>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public Nullable<int> MARKA { get; set; }
        public Nullable<int> KATEGORI { get; set; }
        public Nullable<int> STOK { get; set; }
        public Nullable<int> FIYAT { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string ACIKLAMA { get; set; }
        public string FOTOGRAF { get; set; }
    
        public virtual TBL_KATEGORI TBL_KATEGORI { get; set; }
        public virtual TBL_MARKA TBL_MARKA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SIPARISKALEMI> TBL_SIPARISKALEMI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_YORUM> TBL_YORUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_URUNOZELLIK> TBL_URUNOZELLIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FAVORI> TBL_FAVORI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEPET> TBL_SEPET { get; set; }
    }
}
