//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADRES
    {
        public int ID { get; set; }
        public Nullable<int> UYEID { get; set; }
        public string IL { get; set; }
        public string ILCE { get; set; }
        public string ADRES { get; set; }
        public string BASLIK { get; set; }
    
        public virtual TBL_UYE TBL_UYE { get; set; }
    }
}
