//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Ticaret.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_URUNOZELLIK
    {
        public int ID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<int> OZELLIKID { get; set; }
        public string OZELLIKVALUE { get; set; }
    
        public virtual TBL_OZELLIK TBL_OZELLIK { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
